### ISSUE TITLE
alignment on multi-line labels for checkbox/radio inputs?

### ISSUE THREAD

**Issue by erikwoods** [sparkdesignsystem/spark-design-system#427]
## Describe The Bug
I could think of a few reasons why we might not want to change anything for this, buuuuut.... go to the Inputs page and give one of the labels a lot of text. You'll see it looks.... kinda janky. Screenshot should speak for itself.

## Screenshot
![screen shot 2018-08-16 at 4 03 40 pm](https://user-images.githubusercontent.com/689000/44232361-ce097180-a16e-11e8-8400-8f936d6edc0a.png)

**Comment by afebbraro** [comment]
@erikwoods thanks for the inquiry! I know @RCopeland had taken a look at label line heights the other day but I'm not sure where he ended up with that. I'll let him chime in here. 

Thanks!

**Comment by RCopeland** [comment]
@erikwoods can you verify its still an issue? I think I had a fix in 2.0.

**Comment by afebbraro** [comment]
@erikwoods did you have time to check if this was still an issue? I'm just cleaning up old issues.

**Comment by yodasw16** [comment]
It's still an issue. I just confirmed it
<img width="460" alt="screen shot 2018-08-28 at 5 00 54 pm" src="https://user-images.githubusercontent.com/308696/44750676-f6388f00-aae3-11e8-9fd6-0d208d981edd.png">

**Comment by yodasw16** [comment]
Cancel that, it's fixed in staging.
<img width="470" alt="screen shot 2018-08-28 at 7 11 40 pm" src="https://user-images.githubusercontent.com/308696/44755947-43bdf780-aaf6-11e8-99d1-1d1768338e0f.png">

**Comment by ptrkcsk** [comment]
I'm still seeing bad alignment with long label text for both checkboxes and radio buttons with Spark v6.0.1.

[Here's an example in CodeSandbox.](https://codesandbox.io/s/znvnl2qx5p)
